#!/usr/bin/python3
import sys

minus,zero,plus = 0, 0, 0

for n in sys.argv[1:]:
    x = float(n)
    if x < 0.0:
        minus += 1
    elif x == 0.0:
        zero += 1
    else:
        plus += 1
        
print("正",plus)
print("負",minus)
print("0",zero)

